### ISSUE TITLE
Copy URL to clipboard

### ISSUE THREAD

**Issue by TanmayPatil105** [ArjunSharda/Searchor#105]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
The URL generated will be directly copied to clipboard

**Provide any alternatives to the feature you've considered**

**Additional information**
Dependencies : `pyperclip` library

**Comment by kaustav202** [comment]
can I work on this @TanmayPatil105 ?

**Comment by TanmayPatil105** [comment]
Sorry! But I have started working on it :)
