### ISSUE TITLE
Searchor CLI

### ISSUE THREAD

**Issue by fr4nkln11** [ArjunSharda/Searchor#112]
I think it would be cool if Searchor could be used directly from the command line and not just when it's called from a python program.

a sample search could be like:
`$ searchor google "coding memes" --open`

If you agree with this idea, please assign me to work on this.
I'm actually very interested in this project, and I would really love to work on improving it, even after Hacktoberfest 2022

**Comment by itskegnh** [comment]
I really like this idea, seems more like a CLT than a CLI, but that seems more appropriate anyway

**Comment by fr4nkln11** [comment]
I was about to use `click` to build the CLI, but I noticed we have already used `typer` for copying links to the clipboard. Should I continue to use `click`, or should I switch to `typer` since it's already a dependency.
