### ISSUE TITLE
Use a single dicitionary instead of multiple class attributes

### ISSUE THREAD

**Issue by fr4nkln11** [ArjunSharda/Searchor#119]
In the CLI app I used the forbidden `eval()` function to generate queries,
We can easily avoid that if searchor used a dictionary were all engines can be called with string keys, and not `eval(f"Engine.{engine}.search()")`.

**Comment by The-Debarghya** [comment]
Can you please specify where to implement the dictionary?
Then maybe I can help.

**Comment by fr4nkln11** [comment]
I'm sorry for replying late,
I suggest it should be in the Engine class,
But I believe @itskegnh should know a better way to implement it

**Comment by dan-pavlov** [comment]
Hi @fr4nkln11, I can refactor `main.py` to keep the existing functionality enum engine definition without using `eval()`, would that an acceptable resolution to this issue? If not, do still please assign this issue to me and I can implement dictionary engine definition instead.

**Comment by fr4nkln11** [comment]
That would be awesome, I only suggested a dictionary because I thought it would be easier to call stuff like this `Engines[engine]` where `engine` would be an argument in the CLI function, but if you think you have a better procedure, I'll gladly welcome it, I don't have much experience in OOP, I could learn a few things from your solution.

**Comment by dan-pavlov** [comment]
Hi @fr4nkln11, I have made this pull request https://github.com/ArjunSharda/Searchor/pull/130 which removes the use of `eval()` in the cli function. With that change, user defined `engine` is just passed as an attribute of `Engine` class, and as each engine is defined as a key-value pair, this ends up retrieving the relevant enum member.
