### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by ArjunSharda** [ArjunSharda/Searchor#37]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
<-- A clear and concise description of the feature. What will it do, what will it affect, etc. -->

Add a pull request template.

**No help needed.**

**Provide any alternatives to the feature you've considered**
N/A

**Additional information**
<-- If you have anything additional to say, you can say it here. Otherwise you can leave this blank. -->

**Comment by Anmol-Baranwal** [comment]
Can I work on this issue? What exactly are you trying to create in the pull request template? Should the statements be in sub-headings?

**Comment by ArjunSharda** [comment]
> Can I work on this issue? What exactly are you trying to create in the pull request template? Should the statements be in sub-headings? Your reply is kindly awaited.

Thank you and yes you can!

So my idea is to make a pull request template where there are headings for each statement and there are questions such as like:

What is this pull request about?
What will this pull request affect?

With private comments describing more in depth about the questions.
