### ISSUE TITLE
Order engines by alphabetical order

### ISSUE THREAD

**Issue by Dynnammo** [ArjunSharda/Searchor#39]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
As many people will propose engines to add, it'll be great to order them alphabetically in the `__init__.py` file in `src/seachor`

**Provide any alternatives to the feature you've considered**
None

**Additional information**
For information I first thought DuckDuckGo wasn't available, and had to go through the code to see I was wrong, therefore this issue

**Comment by ArjunSharda** [comment]
I completely understand. I will work on this. Thanks for pointing this out!

**Comment by ArjunSharda** [comment]
Update: Your issue shall be solved in v2.1.0. I really apologize for the difficulty for finding the search engines, and really appreciated that you pointed this out, once again.
