### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by Anmol-Baranwal** [ArjunSharda/Searchor#44]
using **CONTRIBUTING.md**

**Comment by ArjunSharda** [comment]
**ELIGIBLE FOR HACKTOBERFEST IF V2.1.1 IS RELEASED AFTER OCTOBER 1ST, 2022 AND BEFORE OCTOBER 31, 2022. READ MORE ABOUT HACKTOBERFEST [HERE](https://hacktoberfest.com/)**

**Comment by Anmol-Baranwal** [comment]
I have already registered for hacktoberfest!
