### ISSUE TITLE
Add PyPi search queries function

### ISSUE THREAD

**Issue by ArjunSharda** [ArjunSharda/Searchor#45]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
<-- A clear and concise description of the feature. What will it do, what will it affect, etc. -->

Add PyPi search queries function to v2.1.2.

**Provide any alternatives to the feature you've considered**
N/A

**Additional information**
<-- If you have anything additional to say, you can say it here. Otherwise you can leave this blank. -->

**ELIGIBLE FOR HACKTOBERFEST IF V2.1.2 IS RELEASED AFTER OCTOBER 1ST, 2022 AND BEFORE OCTOBER 31, 2022. READ MORE ABOUT HACKTOBERFEST [HERE](https://hacktoberfest.com/)**

**Comment by codemaniac-sahil** [comment]
Would you please assign me this issue.

**Comment by codemaniac-sahil** [comment]
Hello @ArjunSharda, would you please assign me this issue.

**Comment by codemaniac-sahil** [comment]
Hello @ArjunSharda, I am getting this error while solving this issue
![Screenshot (18)](https://user-images.githubusercontent.com/58036566/193395476-78f81b24-bef3-4175-bc2f-f48e5c0fe157.png)

**Comment by codemaniac-sahil** [comment]
@ArjunSharda, would you please check my pull request.
