### ISSUE TITLE
Add Ebay search queries function

### ISSUE THREAD

**Issue by ArjunSharda** [ArjunSharda/Searchor#47]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
<-- A clear and concise description of the feature. What will it do, what will it affect, etc. -->

Adds Ebay search query function
(v2.1.2)

**Provide any alternatives to the feature you've considered**
N/A

**Additional information**
<-- If you have anything additional to say, you can say it here. Otherwise you can leave this blank. -->

**ELIGIBLE FOR HACKTOBERFEST IF V2.1.2 IS RELEASED AFTER OCTOBER 1ST, 2022 AND BEFORE OCTOBER 31, 2022. READ MORE ABOUT HACKTOBERFEST [HERE](https://hacktoberfest.com/)**

**Comment by logic-404** [comment]
Can you assign me the issue please
