### ISSUE TITLE
Additional Query Parameters

### ISSUE THREAD

**Issue by m9m** [ArjunSharda/Searchor#49]
**Describe the feature**
This feature would aim to expand upon the previous Engine class by adding additional (and optional) query parameters that are specific to each URL. This could be, for example,

1. https://www.google.com/search?q=someSearch&num=10 | generate a URL that will fetch a specific # of results for a query
2. https://chrome.google.com/webstore/search/someSearc?_feature=5stars | generate a URL that will fetch only 5 star extensions

as result of changing the Engine class to support this, the search function would also be tweaked in the process.

**Provide any alternatives to the feature you've considered**
Allowing the search function to directly accept additional query params as kwargs or a dictionary parameter to allow broader functionality at the user's discretion.  This is similar to the original proposal.

**Additional information**
This is based off the assumption that this project would want to move beyond minimalistic search querying. In the case a user would want to generate a URL with additional query parameters past the standard search query, they would have to manually write a wrapper for the search function which is for sure an inconvenience.

**Comment by ArjunSharda** [comment]
Great idea! Thanks for submitting.

**Comment by m9m** [comment]
Could you assign this task to me?
