### ISSUE TITLE
Open URL in the browser

### ISSUE THREAD

**Issue by SinghalChinmay** [ArjunSharda/Searchor#51]
**Describe the feature**
This feature will ask the user (using a optional parameter) if they want to open the outputted url in their default browser.

**Comment by ArjunSharda** [comment]
Hi. Thanks for this idea! I have a question though. How would this be used? There are multiple uses of Searchor, for like bots, small projects, etc. I don't get how this would work. I appreciate your idea again but could you describe a little more on what you specifically mean?

**Comment by SinghalChinmay** [comment]
If people want to open the link directly in their browsers, for example - If in a bot, you provide it a query "Hello World", and it returns the url, but using this method we can open that url in the browser too!

Also this feature would be optional, so if a user wants only the url to be outputted, and not to be opened in the browser, then he can opt for that too.

**Comment by ArjunSharda** [comment]
> If people want to open the link directly in their browsers, for example - If in a bot, you provide it a query "Hello World", and it returns the url, but using this method we can open that url in the browser too!
> 
> Also this feature would be optional, so if a user wants only the url to be outputted, and not to be opened in the browser, then he can opt for that too.

Are you saying for this to be related to the terminal?

**Comment by SinghalChinmay** [comment]
> > If people want to open the link directly in their browsers, for example - If in a bot, you provide it a query "Hello World", and it returns the url, but using this method we can open that url in the browser too!
> > Also this feature would be optional, so if a user wants only the url to be outputted, and not to be opened in the browser, then he can opt for that too.
> 
> Are you saying for this to be related to the console only?

Yeah, but I guess this thing can be used almost everywhere...

**Comment by ArjunSharda** [comment]
Sorry if I was confusing you. What's the purpose of this PR if all links are actually clickable and can open in your default browser? Like in a console you can click the link and it will use your default browser. I'm just confused on what you mean. Do you mean like if you run the code with that feature enabled it will immediately open a new window with that link?

**Comment by SinghalChinmay** [comment]
Yeah, that's what I meant.

Sorry, I wasn't able to explain things properly!

**Comment by ArjunSharda** [comment]
It is workable on if you want still.

**Comment by SinghalChinmay** [comment]
Sure!

**Comment by ArjunSharda** [comment]
This feature request might take some time though. Just a notice

**Comment by SinghalChinmay** [comment]
Yeah, no problems!
