### ISSUE TITLE
Naming convention for engine names not mentioned anywhere

### ISSUE THREAD

**Issue by a-1an** [ArjunSharda/Searchor#63]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
Lets the user know the naming convention  used for engines

**Provide any alternatives to the feature you've considered**
Any other alternatives to the feature request you are asking for if we decide not to go with your feature request?

**Additional information**

**Comment by a-1an** [comment]
can you assign this to me?

**Comment by ArjunSharda** [comment]
Sure! We can just add a tiny comment in Searchor's `__init__.py` file which states that it's A-Z alphabetical order
