### ISSUE TITLE
Add Medium Search queries function

### ISSUE THREAD

**Issue by ArjunSharda** [ArjunSharda/Searchor#64]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
<-- A clear and concise description of the feature. What will it do, what will it affect, etc. -->

Adds medium search query function (https://medium.com/)

**Provide any alternatives to the feature you've considered**
Any other alternatives to the feature request you are asking for if we decide not to go with your feature request?

N/A

**Additional information**
<-- If you have anything additional to say, you can say it here. Otherwise you can leave this blank. -->

N/A

**Comment by RohanKaran** [comment]
@ArjunSharda Can you please assign this issue to me?
