### ISSUE TITLE
Add Reddit search

### ISSUE THREAD

**Issue by RohanKaran** [ArjunSharda/Searchor#78]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
<-- A clear and concise description of the feature. What will it do, what will it affect, etc. -->
- Adds search query for Reddit

**Provide any alternatives to the feature you've considered**
Any other alternatives to the feature request you are asking for if we decide not to go with your feature request?

**Additional information**
<-- If you have anything additional to say, you can say it here. Otherwise you can leave this blank. -->

**Comment by ChairbfBackup** [comment]
can i work on this
