### ISSUE TITLE
Add blogger search query

### ISSUE THREAD

**Issue by RohanKaran** [ArjunSharda/Searchor#79]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
<-- A clear and concise description of the feature. What will it do, what will it affect, etc. -->
- Adds search query for blogger.com

**Provide any alternatives to the feature you've considered**
Any other alternatives to the feature request you are asking for if we decide not to go with your feature request?

**Additional information**
<-- If you have anything additional to say, you can say it here. Otherwise you can leave this blank. -->

**Comment by ArjunSharda** [comment]
Hi. I don't think there's a search option for Blogger. Are you able to search on Blogger?

**Comment by RohanKaran** [comment]
> Hi @RohanKaran , thanks for the feature request. I don't think there's a search option for Blogger. Are you able to search on Blogger?

Not directly on blogger, but we can use https://www.searchblogspot.com/search?q={query} to retrieve blog posts.

**Comment by ArjunSharda** [comment]
> > Hi @RohanKaran , thanks for the feature request. I don't think there's a search option for Blogger. Are you able to search on Blogger?
> 
> Not directly on blogger, but we can use [https://www.searchblogspot.com/search?q={query}](https://www.searchblogspot.com/search?q=%7Bquery%7D) to retrieve blog posts.

Ah. Sure. I can work on this if you want, or if you want you can do it.
