### ISSUE TITLE
Multiple incorrect engine names

### ISSUE THREAD

**Issue by andrewgordonyule** [ArjunSharda/Searchor#82]
**Bug Description**
Searching for a query using the Atlassian and Lycos engines throws an error due to incorrect spelling in __init__.py file.

**Screenshots**
![image](https://user-images.githubusercontent.com/49346970/193430142-aaf5f999-1c5f-45c0-91b3-05041a4181cb.png)

**Additional context**
I will raise a PR to fix this.

**Comment by ArjunSharda** [comment]
Fixed via #83. Thank you so much for raising this!
