### ISSUE TITLE
Add auto labeler for PRs and Issues

### ISSUE THREAD

**Issue by ArjunSharda** [ArjunSharda/Searchor#85]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
<-- A clear and concise description of the feature. What will it do, what will it affect, etc. -->

This workflow will automatically label PRs and Issues based on the text of the issue / PR.

**Provide any alternatives to the feature you've considered**
Any other alternatives to the feature request you are asking for if we decide not to go with your feature request?

**Additional information**
<-- If you have anything additional to say, you can say it here. Otherwise you can leave this blank. -->

I can work on this.

**Comment by ArjunSharda** [comment]
Not going to work on this atm anymore. If anyone wants to take this up, ping me.

**Comment by Mitternachtsmond** [comment]
I would like to try this
Please assign me this issue

**Comment by blackbeareatsfish** [comment]
This may help: https://github.com/apps/auto-labeler
