### ISSUE TITLE
Adding more engines

### ISSUE THREAD

**Issue by kailashchoudhary11** [ArjunSharda/Searchor#88]
Add engine for instagram and flipkart!

**Comment by ArjunSharda** [comment]
Hi @kailashchoudhary11 ,

Good idea! However, this will be paused due to v2.2.0 coming and then this can start being worked on.

**Comment by kailashchoudhary11** [comment]
Okay Please Let me know as soon as v2.20 is released!

**Comment by ArjunSharda** [comment]
Sure! Will ping you here.

**Comment by ArjunSharda** [comment]
@kailashchoudhary11

**Comment by kailashchoudhary11** [comment]
Can I add now?

**Comment by ArjunSharda** [comment]
Yes.
