### ISSUE TITLE
Add Custom search engine

### ISSUE THREAD

**Issue by ArjunSharda** [ArjunSharda/Searchor#91]
**Is your feature request related to a problem? Please describe if so, otherwise leave this blank..**

**Describe the feature**
<-- A clear and concise description of the feature. What will it do, what will it affect, etc. -->

This adds a custom search engine. As a user of Searchor, I can see it's really annoying to not have the option and is one of the disadvantages of Searchor. I think a custom search engine would be really useful.

**Provide any alternatives to the feature you've considered**
Any other alternatives to the feature request you are asking for if we decide not to go with your feature request?

**Additional information**
<-- If you have anything additional to say, you can say it here. Otherwise you can leave this blank. -->

**Comment by akshaykhoje** [comment]
Hello @ArjunSharda!

I wish to add a few more search engines to the collection. 
Please assign me this feature addition issue.

**Comment by dan-pavlov** [comment]
Hi there! I'd like to work on this issue, could you assign it to me?

**Comment by AshutoshJawanpuria** [comment]
Hi! Can you let me work on this issue??

**Comment by ArjunSharda** [comment]
> Hi! Can you let me work on this issue??

Hi, I think @dan-pavlov is working on this, so sorry it's already taken. Thank you though for offering your help.

**Comment by ArjunSharda** [comment]
> Hi there! I'd like to work on this issue, could you assign it to me?

Hi! I don't think you're working on this, are you working on this still?

**Comment by dan-pavlov** [comment]
Hi @ArjunSharda, apologies for such a late reply, but I have made a pull request https://github.com/ArjunSharda/Searchor/pull/122 that should fulfil the requirements in this issue. I'll be checking on that PR every day in case you make and change requests.
